<a target="_blank" href="https://colab.research.google.com/github/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

[View source code](https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb) | [Read notebook in online book format](https://dev.mrdbourke.com/zero-to-mastery-ml/introduction-to-numpy/)

# A Quick Introduction to Numerical Data Manipulation with Python and NumPy

## What is NumPy?

[NumPy](https://numpy.org/doc/stable/index.html) stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play.

<img src="../images/numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>

## Why NumPy?

You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. [Vectorization](https://en.wikipedia.org/wiki/Vectorization) aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

## What does this notebook cover?

The NumPy library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses on the main concepts of NumPy and the `ndarray` datatype.

You can think of the `ndarray` datatype as a very flexible array of numbers.

More specifically, we'll look at:
* NumPy datatypes & attributes
* Creating arrays
* Viewing arrays & matrices (indexing)
* Manipulating & comparing arrays
* Sorting arrays
* Use cases (examples of turning things into numbers)

After going through it, you'll have the base knolwedge of NumPy you need to keep moving forward.

## Where can I get help?
If you get stuck or think of something you'd like to do which this notebook doesn't cover, don't fear!

The recommended steps you take are:
1. **Try it** - Since NumPy is very friendly, your first step should be to use what you know and try figure out the answer to your own question (getting it wrong is part of the process). If in doubt, run your code.
2. **Search for it** - If trying it on your own doesn't work, since someone else has probably tried to do something similar, try searching for your problem in the following places (either via a search engine or direct):
    * [NumPy documentation](https://numpy.org/doc/stable/index.html) - The ground truth for everything NumPy, this resource covers all of the NumPy functionality.
    * [Stack Overflow](https://stackoverflow.com/) - This is the developers Q&A hub, it's full of questions and answers of different problems across a wide range of software development topics and chances are, there's one related to your problem.
    * [ChatGPT](https://chat.openai.com/) - ChatGPT is very good at explaining code, however, it can make mistakes. Best to verify the code it writes first before using it. Try asking "Can you explain the following code for me? {your code here}" and then continue with follow up questions from there. Avoid straight copying and pasting and instead, only use things that you could yourself reproduce with adequate effort.
    
An example of searching for a NumPy function might be:

> "how to find unique elements in a numpy array"

Searching this on Google leads to the NumPy documentation for the `np.unique()` function: https://numpy.org/doc/stable/reference/generated/numpy.unique.html

The next steps here are to read through the documentation, check the examples and see if they line up to the problem you're trying to solve. 

If they do, **rewrite the code** to suit your needs, run it, and see what the outcomes are.

3. **Ask for help** - If you've been through the above 2 steps and you're still stuck, you might want to ask your question on [Stack Overflow](https://www.stackoverflow.com). Be as specific as possible and provide details on what you've tried.

Remember, you don't have to learn all of the functions off by heart to begin with. 

What's most important is continually asking yourself, "what am I trying to do with the data?".

Start by answering that question and then practicing finding the code which does it.

Let's get started.

## 0. Importing NumPy

To get started using NumPy, the first step is to import it. 

The most common way (and method you should use) is to import NumPy as the abbreviation `np`.

If you see the letters `np` used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [2]:
import numpy as np

# Check the version
print(np.__version__)

2.1.1

## 1. DataTypes and attributes

> **Note:** Important to remember the main type in NumPy is `ndarray`, even seemingly different kinds of arrays are still `ndarray`'s. This means an operation you do on one array, will work on another.

In [3]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [4]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [6]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Anatomy of an array

<img src="../images/numpy-anatomy-of-an-array-updated.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimension (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-dimensional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

### pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.

In [10]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), 
                                    columns=['a', 'b', 'c'])
df

   a  b  c
0  5  8  0
1  3  3  2
2  1  6  7
3  7  3  9
4  6  6  7

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
df2 = pd.DataFrame(a2)
df2

     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers
* Searching the documentation example (finding `np.unique()` and using it)

In [13]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [14]:
simple_array = np.array((1, 2, 3))
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [15]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [17]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [18]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[8, 7, 6],
       [4, 2, 7],
       [6, 0, 6],
       [0, 8, 5],
       [6, 2, 9]])

In [22]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.47811645, 0.49437395, 0.09426995],
       [0.80062461, 0.41609157, 0.45268566],
       [0.24531914, 0.56982162, 0.36856519],
       [0.32292926, 0.03760924, 0.13312765],
       [0.66844485, 0.88781517, 0.21807957]])

In [23]:
np.random.random((5, 3))

array([[0.96868201, 0.87777028, 0.21900062],
       [0.88225041, 0.73815918, 0.83321165],
       [0.14038979, 0.79643185, 0.2741666 ],
       [0.48166491, 0.74364069, 0.75385132],
       [0.58920305, 0.43270563, 0.42922598]])

In [24]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.90225603, 0.76253433, 0.84856067],
       [0.8961939 , 0.37019149, 0.00568981],
       [0.78797133, 0.07953581, 0.99870521],
       [0.07481087, 0.74846133, 0.0788899 ],
       [0.40156115, 0.80716411, 0.37204142]])

In [25]:
np.random.rand(5, 3)

array([[0.80767414, 0.62863218, 0.32492877],
       [0.71402148, 0.06601142, 0.16626604],
       [0.81986587, 0.75875945, 0.73266779],
       [0.4233863 , 0.52077358, 0.21571921],
       [0.75862881, 0.65817717, 0.74667541]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [ ]:
# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

In [27]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

Let's see it in action again, we'll stay consistent and set the random seed to 0.

In [28]:
# Set random seed to same number as above
np.random.seed(0)

# The same random numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [29]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

   0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

### What unique values are in the array a3?

Now you've seen a few different ways to create arrays, as an exercise, try find out what NumPy function you could use to find the unique values are within the `a3` array.

You might want to search some like, "how to find the unqiue values in a numpy array".

In [30]:
# Your code here

## 3. Viewing arrays and matrices (indexing)

Remember, because arrays and matrices are both `ndarray`'s, they can be viewed in similar ways.

Let's check out our 3 arrays again.

In [89]:
#import
import numpy as np

In [90]:
#create a1
a1 =  np.array([1,2,3])

In [91]:
#create a2
a2 = np.array([[1,2,3],[4,5,6]])

In [92]:
#create a3
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

Array shapes are always listed in the format `(row, column, n, n, n...)` where `n` is optional extra dimensions.

In [93]:
#first element a1
a1[0]

np.int64(1)

In [94]:
#first element a2
a2[0]

array([1, 2, 3])

In [95]:
#first element a3
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [97]:
a3.shape

(2, 3, 3)

In [99]:
# Get 2nd row (index 1) of a2
a3[:,:2,:]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [98]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:,:,:2]

array([[[1, 2],
        [4, 5],
        [7, 8]],

       [[1, 2],
        [4, 5],
        [7, 8]]])

This takes a bit of practice, especially when the dimensions get higher. Usually, it takes me a little trial and error of trying to get certain values, viewing the output in the notebook and trying again.

NumPy arrays get printed from outside to inside. This means the number at the end of the shape comes first, and the number at the start of the shape comes last.

In [102]:
#create a4 random size=(2,3,4,5)
a4 = np.random.randint(10,size=(2,3,4,5))

In [103]:
# a4.ndim
a4.ndim

4

In [105]:
a4

array([[[[6, 2, 2, 6, 4],
         [1, 0, 2, 6, 0],
         [8, 3, 0, 2, 6],
         [4, 6, 0, 9, 4]],

        [[6, 5, 7, 7, 5],
         [7, 7, 6, 6, 6],
         [2, 2, 6, 7, 0],
         [3, 4, 1, 5, 9]],

        [[4, 6, 1, 0, 9],
         [2, 9, 3, 0, 9],
         [7, 4, 2, 8, 9],
         [7, 3, 1, 2, 0]]],


       [[[6, 0, 2, 8, 0],
         [4, 1, 6, 5, 9],
         [2, 1, 6, 7, 0],
         [3, 5, 3, 1, 5]],

        [[4, 9, 8, 3, 5],
         [2, 1, 2, 5, 9],
         [9, 8, 3, 5, 5],
         [9, 4, 7, 9, 9]],

        [[4, 5, 7, 3, 7],
         [4, 1, 5, 8, 0],
         [2, 1, 2, 9, 2],
         [6, 6, 2, 9, 7]]]], dtype=int32)

In [104]:
a4.shape

(2, 3, 4, 5)

In [106]:
# Get only the first 4 numbers of each single vector
a4[:,:,:,:4]

array([[[[6, 2, 2, 6],
         [1, 0, 2, 6],
         [8, 3, 0, 2],
         [4, 6, 0, 9]],

        [[6, 5, 7, 7],
         [7, 7, 6, 6],
         [2, 2, 6, 7],
         [3, 4, 1, 5]],

        [[4, 6, 1, 0],
         [2, 9, 3, 0],
         [7, 4, 2, 8],
         [7, 3, 1, 2]]],


       [[[6, 0, 2, 8],
         [4, 1, 6, 5],
         [2, 1, 6, 7],
         [3, 5, 3, 1]],

        [[4, 9, 8, 3],
         [2, 1, 2, 5],
         [9, 8, 3, 5],
         [9, 4, 7, 9]],

        [[4, 5, 7, 3],
         [4, 1, 5, 8],
         [2, 1, 2, 9],
         [6, 6, 2, 9]]]], dtype=int32)

`a4`'s shape is (2, 3, 4, 5), this means it gets displayed like so:
* Inner most array = size 5
* Next array = size 4
* Next array = size 3
* Outer most array = size 2

## 4. Manipulating and comparing arrays
* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than Python's `.sum()` for NumPy arrays
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T` 
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Arithmetic

In [107]:
#a1
a1

array([1, 2, 3])

In [109]:
#ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
# Add two arrays
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [111]:
# Subtract two arrays
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [112]:
# Multiply two arrays
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [113]:
# a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
a1

array([1, 2, 3])

In [119]:
# Multiply two arrays
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [120]:
# a1.shape, a2.shape
a1.shape , a2.shape

((3,), (2, 3))

In [121]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [123]:
# This will error as the arrays have a different number of dimensions (2, 3) vs. (2, 3, 3) 
a3 * a1

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]])

### Broadcasting

- What is broadcasting?
    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
    
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

In [124]:
#a1
a1

array([1, 2, 3])

In [125]:
#shape of a1
a1.shape

(3,)

In [126]:
#shape of a2
a2.shape

(2, 3)

In [127]:
#a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
#sum
a2 + a1

array([[2, 4, 6],
       [5, 7, 9]])

In [129]:
#sum with 2
a2 +2

array([[3, 4, 5],
       [6, 7, 8]])

In [131]:
# Raises an error because there's a shape mismatch (2, 3) vs. (2, 3, 3)
a3 + a1

array([[[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]]])

In [132]:
# Divide two arrays
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [133]:
# Divide two arrays a1,a2
a2//a1

array([[1, 1, 1],
       [4, 2, 2]])

In [134]:
# Take an array to a power
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [135]:
# You can also use np.square()
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [136]:
# Modulus divide (what's the remainder)
a2 % 2

array([[1, 0, 1],
       [0, 1, 0]])

You can also find the log or exponential of an array using `np.log()` and `np.exp()`.

In [137]:
# Find the log of an array
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [138]:
# Find the exponential of an array
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

### Aggregation

Aggregation - bringing things together, doing a similar thing on a number of things.

In [139]:
# a1
a1

array([1, 2, 3])

In [140]:
#sum a1 elements by python
sum(a1)

np.int64(6)

In [141]:
#sum a1 elements by numpy
np.sum(a1)

np.int64(6)

**Tip:** Use NumPy's `np.sum()` on NumPy arrays and Python's `sum()` on Python `list`s.

In [142]:
#massive_array(random)
massive_array = np.random.random(100)

In [143]:
 # Python sum()
 # NumPy np.sum()
%timeit sum(massive_array)
%timeit np.sum(massive_array)

9.31 μs ± 288 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.45 μs ± 57.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

Notice `np.sum()` is faster on the Numpy array (`numpy.ndarray`) than Python's `sum()`.

Now let's try it out on a Python list.

In [145]:
#massive_list
massive_list = [1,2,3,4,5,5]

In [146]:
#compare time
# Python sum()
 # NumPy np.sum()
%timeit sum(massive_list)
%timeit np.sum(massive_list)

105 ns ± 1.51 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
5.57 μs ± 49.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

NumPy's `np.sum()` is still fast but Python's `sum()` is faster on Python `list`s.

In [147]:
# a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
# Find the mean
np.mean(a2)

np.float64(3.5)

In [149]:
# Find the max
np.max(a2)

np.int64(6)

In [150]:
# Find the min
np.min(a2)

np.int64(1)

In [151]:
# Find the standard deviation
np.std(a2)

np.float64(1.707825127659933)

In [152]:
# Find the variance
np.var(a2)

np.float64(2.9166666666666665)

In [153]:
# The standard deviation is the square root of the variance
np.sqrt(np.var(a2))

np.float64(1.707825127659933)

**What's mean?**

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

**What's standard deviation?**

[Standard deviation](https://www.mathsisfun.com/data/standard-deviation.html) is a measure of how spread out numbers are.

**What's variance?**

The [variance](https://www.mathsisfun.com/data/standard-deviation.html) is the averaged squared differences of the mean.

To work it out, you:
1. Work out the mean
2. For each number, subtract the mean and square the result
3. Find the average of the squared differences

### Reshaping

In [154]:
# a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
# a2.shape
a2.shape

(2, 3)

In [159]:
a3.shape

(2, 3, 3)

In [160]:
a3.reshape(6,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
# a2 + a3
a2 + a3.reshape(6,3)

ValueError: operands could not be broadcast together with shapes (2,3) (6,3)

In [ ]:
a3[: , :2,:]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a2 + a3[: , :2,:]

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

### Transpose

A tranpose reverses the order of the axes. 

For example, an array with shape `(2, 3)` becomes `(3, 2)`.

In [165]:
# a2.shape
a2.shape

(2, 3)

In [166]:
#a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
# a2.T
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [170]:
#transpose
np.transpose(a2)

array([[1, 4],
       [2, 5],
       [3, 6]])

For larger arrays, the default value of a tranpose is to swap the first and last axes.

For example, `(5, 3, 3)` -> `(3, 3, 5)`.

In [171]:
# Check to see if the reverse shape is same as tranpose shape
a2.T.shape == a2.shape[::-1]

True

You can see more advanced forms of tranposing in the NumPy documentation under [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html).

### Dot product

The main two rules for dot product to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
  
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`
 
**Note:** In NumPy, `np.dot()` and `@` can be used to acheive the same result for 1-2 dimension arrays. However, their behaviour begins to differ at arrays with 3+ dimensions.

In [172]:
#create mat1(3,3) mat2(3,2) RANDOM
mat1 = np.random.randint(6,size=(3,3))
mat2 = np.random.randint(6,size=(3,2))

In [173]:
# mat1
mat1

array([[3, 0, 0],
       [5, 4, 0],
       [1, 4, 0]], dtype=int32)

In [174]:
# mat2
mat2

array([[4, 1],
       [3, 2],
       [0, 0]], dtype=int32)

In [176]:
#dot
np.dot(mat1, mat2)

array([[12,  3],
       [32, 13],
       [16,  9]], dtype=int32)

In [177]:
# Can also achieve np.dot() with "@" 
# (however, they may behave differently at 3D+ arrays)

mat1 @ mat2

array([[12,  3],
       [32, 13],
       [16,  9]], dtype=int32)

In [178]:
#create mat3(4,3) mat4(4,3) RANDOM
mat3 = np.random.randint(6,size=(4,3))
mat4 = np.random.randint(6,size=(4,3))

In [181]:
# mat4
mat4.shape , mat3.shape

((4, 3), (4, 3))

In [182]:
#how to fix it ?
mat3.T

array([[0, 1, 4, 0],
       [5, 4, 2, 0],
       [5, 2, 4, 5]], dtype=int32)

In [183]:
# Dot product
mat4 @ mat3.T

array([[30, 18, 18, 15],
       [25, 17, 18, 10],
       [ 0,  2,  8,  0],
       [30, 21, 30, 15]], dtype=int32)

### Comparison operators 

Finding out if one array is larger, smaller or equal to another.

In [184]:
# a1
a1

array([1, 2, 3])

In [185]:
# a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
# a1 > a2
a1>a2

array([[False, False, False],
       [False, False, False]])

In [187]:
# a1 >= a2
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [188]:
# a1 > 5
a1 > 5

array([False, False, False])

In [189]:
# a1 == a1
a1 == a1

array([ True,  True,  True])

In [190]:
# a1 == a2
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## 5. Sorting arrays

* [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) - sort values in a specified dimension of an array.
* [`np.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) - return the indices to sort the array on a given axis.
* [`np.argmax()`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) - return the index/indicies which gives the highest value(s) along an axis.
* [`np.argmin()`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) - return the index/indices which gives the lowest value(s) along an axis.

In [199]:
# random_array
random_array = np.random.randint(10 , size=(2,3))
random_array

array([[1, 9, 4],
       [8, 9, 8]], dtype=int32)

In [200]:
#sort
np.sort(random_array)

array([[1, 4, 9],
       [8, 8, 9]], dtype=int32)

In [201]:
#argsort
np.argsort(random_array)

array([[0, 2, 1],
       [0, 2, 1]])

In [203]:
# a1
a1

array([1, 2, 3])

In [204]:
# Return the indices that would sort an array
np.argsort(a1)

array([0, 1, 2])

In [205]:
#argmin
np.argmin(a1)

np.int64(0)

In [206]:
# random_array
random_array

array([[1, 9, 4],
       [8, 9, 8]], dtype=int32)

In [207]:
# Down the vertical argmax
np.argmax(random_array , axis=1)

array([1, 1])

In [208]:
# Across the horizontal argmin
np.argmin(random_array , axis=0)

array([0, 0, 0])