<a target="_blank" href="https://colab.research.google.com/github/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

[View source code](https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb) | [Read notebook in online book format](https://dev.mrdbourke.com/zero-to-mastery-ml/introduction-to-numpy/)

# A Quick Introduction to Numerical Data Manipulation with Python and NumPy

## What is NumPy?

[NumPy](https://numpy.org/doc/stable/index.html) stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play.

<img src="../images/numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>

## Why NumPy?

You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. [Vectorization](https://en.wikipedia.org/wiki/Vectorization) aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

## What does this notebook cover?

The NumPy library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses on the main concepts of NumPy and the `ndarray` datatype.

You can think of the `ndarray` datatype as a very flexible array of numbers.

More specifically, we'll look at:
* NumPy datatypes & attributes
* Creating arrays
* Viewing arrays & matrices (indexing)
* Manipulating & comparing arrays
* Sorting arrays
* Use cases (examples of turning things into numbers)

After going through it, you'll have the base knolwedge of NumPy you need to keep moving forward.

## Where can I get help?
If you get stuck or think of something you'd like to do which this notebook doesn't cover, don't fear!

The recommended steps you take are:
1. **Try it** - Since NumPy is very friendly, your first step should be to use what you know and try figure out the answer to your own question (getting it wrong is part of the process). If in doubt, run your code.
2. **Search for it** - If trying it on your own doesn't work, since someone else has probably tried to do something similar, try searching for your problem in the following places (either via a search engine or direct):
    * [NumPy documentation](https://numpy.org/doc/stable/index.html) - The ground truth for everything NumPy, this resource covers all of the NumPy functionality.
    * [Stack Overflow](https://stackoverflow.com/) - This is the developers Q&A hub, it's full of questions and answers of different problems across a wide range of software development topics and chances are, there's one related to your problem.
    * [ChatGPT](https://chat.openai.com/) - ChatGPT is very good at explaining code, however, it can make mistakes. Best to verify the code it writes first before using it. Try asking "Can you explain the following code for me? {your code here}" and then continue with follow up questions from there. Avoid straight copying and pasting and instead, only use things that you could yourself reproduce with adequate effort.
    
An example of searching for a NumPy function might be:

> "how to find unique elements in a numpy array"

Searching this on Google leads to the NumPy documentation for the `np.unique()` function: https://numpy.org/doc/stable/reference/generated/numpy.unique.html

The next steps here are to read through the documentation, check the examples and see if they line up to the problem you're trying to solve. 

If they do, **rewrite the code** to suit your needs, run it, and see what the outcomes are.

3. **Ask for help** - If you've been through the above 2 steps and you're still stuck, you might want to ask your question on [Stack Overflow](https://www.stackoverflow.com). Be as specific as possible and provide details on what you've tried.

Remember, you don't have to learn all of the functions off by heart to begin with. 

What's most important is continually asking yourself, "what am I trying to do with the data?".

Start by answering that question and then practicing finding the code which does it.

Let's get started.

## 0. Importing NumPy

To get started using NumPy, the first step is to import it. 

The most common way (and method you should use) is to import NumPy as the abbreviation `np`.

If you see the letters `np` used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [27]:
import numpy as np
# Check the version
np.__version__

'2.2.6'

## 1. DataTypes and attributes

> **Note:** Important to remember the main type in NumPy is `ndarray`, even seemingly different kinds of arrays are still `ndarray`'s. This means an operation you do on one array, will work on another.

In [28]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1,2,3])
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1,2,3],[4,5,6]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
])

In [30]:
#a1
a1.shape , a1.ndim , a1.dtype , a1.size , type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [31]:
#a2
a2.shape , a2.ndim , a2.dtype , a2.size , type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [32]:
#a3
a3.shape , a3.ndim , a3.dtype , a3.size , type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [33]:
#print a1
a1

array([1, 2, 3])

In [34]:
#print a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#print a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Anatomy of an array

<img src="../images/numpy-anatomy-of-an-array-updated.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimension (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-dimensional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

### pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.

In [40]:
import pandas as pd 
df = pd.DataFrame(np.random.randint(10,size=(5,3)), columns=['a','b','c'])
df

   a  b  c
0  2  9  0
1  4  8  1
2  3  4  9
3  6  6  0
4  7  4  9

In [41]:
#print a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
df2 = pd.DataFrame(a2)
df2

   0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers
* Searching the documentation example (finding `np.unique()` and using it)

In [74]:
# Create a simple array
a4 = np.array([1,2,3])

In [75]:
#dtype
a4.dtype

dtype('int64')

In [77]:
# Create an array of ones
ones =  np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [79]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

In [80]:
# Create an array of zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
zeros.dtype

dtype('float64')

In [83]:
# Create an array within a range of values
ran = np.arange(0,10,2)
ran

array([0, 2, 4, 6, 8])

In [85]:
# Random array
rand1 = np.random.randint(10,size=(2,3))
rand1

array([[6, 8, 2],
       [0, 0, 1]], dtype=int32)

In [87]:
# Random array of floats (between 0 & 1)
rand2 = np.random.rand(2,3)
rand2

array([[0.89897267, 0.1668971 , 0.33095894],
       [0.59195931, 0.98824601, 0.52176919]])

In [88]:
rand2 = np.random.random((2,3))
rand2

array([[0.34312124, 0.14760935, 0.24160215],
       [0.72701901, 0.28423457, 0.86743348]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [89]:
# Set random seed to 0
np.random.seed(2)
# Make 'random' numbers
rand1 = np.random.randint(10,size=(2,3))
rand1

array([[8, 8, 6],
       [2, 8, 7]], dtype=int32)

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.